package Views.Reports;

import DigyFenix.*;
import Utilidades.JReport;
import Utils.HbUtils;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import javax.persistence.EntityManager;
import net.sf.jasperreports.view.JasperViewer;
import org.hibernate.Session;
import org.hibernate.jdbc.Work;

/**
 *
 * @author echacon
 */
public class VReporteCumpleanios extends javax.swing.JInternalFrame {

    HashMap<String, Object> mapFields = new HashMap<>();

    Connection conexion;

    /**
     * Creates new form v_empresa
     */
    public VReporteCumpleanios() {
        initComponents();

        DFUtils.setColorABotton(btnTrasladar);
        EntityManager em = HbUtils.getEntityManager();
        em.getTransaction().begin();
        Session session = em.unwrap(Session.class);
        session.doWork(new Work() {
            @Override
            public void execute(Connection cnctn) throws SQLException {
                conexion = cnctn;
            }
        });
        em.getTransaction().commit();
        em.close();

    }

    private void generar() {
        String reporte = "Cumple.jasper";
        int mes = cbxMes.getSelectedIndex() + 1;
        Map<String, Object> parametros = new HashMap<>();
        parametros.put("idmes", mes);

        try {
            JasperViewer visor = new JasperViewer(JReport.generarReporte(reporte, parametros, conexion), false);
            visor.setVisible(true);
            this.dispose();
        } catch (Exception e) {
            System.out.println("Excepcion controlada: " + e.toString());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTrasladar = new javax.swing.JButton();
        cbxMes = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Listado de cumpleaños");
        setMaximumSize(new java.awt.Dimension(250, 190));
        setMinimumSize(new java.awt.Dimension(250, 190));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(250, 190));
        getContentPane().setLayout(null);

        btnTrasladar.setBackground(new java.awt.Color(0, 153, 102));
        btnTrasladar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnTrasladar.setForeground(new java.awt.Color(255, 255, 255));
        btnTrasladar.setText("Generar");
        btnTrasladar.setBorder(null);
        btnTrasladar.setBorderPainted(false);
        btnTrasladar.setContentAreaFilled(false);
        btnTrasladar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTrasladar.setOpaque(false);
        btnTrasladar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrasladarActionPerformed(evt);
            }
        });
        getContentPane().add(btnTrasladar);
        btnTrasladar.setBounds(60, 100, 140, 40);

        cbxMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        getContentPane().add(cbxMes);
        cbxMes.setBounds(50, 40, 160, 30);

        jLabel1.setText("Mes ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 20, 27, 16);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTrasladarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrasladarActionPerformed
        generar();
    }//GEN-LAST:event_btnTrasladarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTrasladar;
    private javax.swing.JComboBox<String> cbxMes;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
