package Views;

import Controladores.DaoDepartamento;
import DigyFenix.*;
import Enums.InsertUpdate;
import Modelos.Departamento;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author echacon
 */
public class VDepartamento extends javax.swing.JInternalFrame {

    HashMap<String, Object> mapFields = new HashMap<>();
    Departamento dep;
    DaoDepartamento daodep;

    /**
     * Creates new form v_empresa
     */
    public VDepartamento() {
        initComponents();

        //Inicio las variables
        nuevaDepartamento();
        daodep = new DaoDepartamento();

        //Configuro los botonos
        DFUtils.setColorABotton(btnGuardar);
        DFUtils.setColorABotton(btnNuevo);

        mapearFiels();

        llenarTablaDepartamentos();

        dep.limpiarFields(true);
        dep.fieldsActivados(false);
    }

    private void mapearFiels() {
        //System.out.println("mapearFiels:" + DFUtils.getMapearFiels(dep.getVariables()));
        mapFields.put("descripcion", txbDescripcion);
        mapFields.put("activo", cbxActivo);
        mapFields.put("cuentaContable", txbCuenta);

        dep.mapearFields(mapFields);
    }

    private void guardar() {
        try {
            boolean nueva = (dep.getIddepartamento() == null);
            //Primero se guardan los datos auxiliares para actualizar ids

            String tipo = "";
            if (nueva) {
                daodep.insertarActualizar(dep, InsertUpdate.INSERTAR);
                tipo = "insertado";
            } else {
                daodep.insertarActualizar(dep, InsertUpdate.ACTUALIZAR);
                tipo = "actualizado";
            }
            llenarTablaDepartamentos();
            DFOptionPane.mostrar_Realizado(dep.getClass().getSimpleName() + " " + tipo + " corretamente");
        } catch (Exception e) {
            DFOptionPane.mostrar_Error(e.toString());
        }
    }

    private void nuevaDepartamento() {
        dep = new Departamento();
        dep.mapearFields(mapFields);
        dep.limpiarFields(true);
        txbDescripcion.requestFocus();
        dep.fieldsActivados(true);
    }

    private void llenarTablaDepartamentos() {
        String encabezado[] = {"Id", "Departamento", "Cuenta Contable"};
        List<Departamento> list = daodep.listar();
        List<String[]> rows = new ArrayList<>();
        list.forEach((t) -> {
            String row[] = {"" + t.getIddepartamento(), t.getDescripcion(), t.getCuentaContable()};
            rows.add(row);
        });

        DFTable.llenarTablaCol0NoEditable(tblDepartamentos, encabezado, rows);
    }

    private void cargarDetalle(String id) {
        try {
            dep = daodep.buscarPorId(Integer.parseInt(id));
            dep.mapearFields(mapFields);
            dep.llenarFields();
            dep.fieldsActivados(true);
        } catch (Exception e) {
            DFOptionPane.mostrar_Error(e.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGuardar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDepartamentos = new javax.swing.JTable();
        tblDepartamentos.getSelectionModel().addListSelectionListener( 
            new ListSelectionListener(){
                public void valueChanged(ListSelectionEvent event){
                    if(!event.getValueIsAdjusting() && (tblDepartamentos.getSelectedRow() >= 0)){
                        cargarDetalle(""+tblDepartamentos.getValueAt(tblDepartamentos.getSelectedRow(), 0));
                    }
                }
            }
        );
        btnNuevo = new javax.swing.JButton();
        txbDescripcion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbxActivo = new javax.swing.JComboBox<>();
        txbCuenta = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Administracion de departamentos");
        setMaximumSize(new java.awt.Dimension(583, 351));
        setMinimumSize(new java.awt.Dimension(448, 354));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(583, 351));
        getContentPane().setLayout(null);

        btnGuardar.setBackground(new java.awt.Color(0, 153, 102));
        btnGuardar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.setBorder(null);
        btnGuardar.setBorderPainted(false);
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.setOpaque(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar);
        btnGuardar.setBounds(360, 260, 80, 30);

        tblDepartamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblDepartamentos);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 10, 550, 160);

        btnNuevo.setBackground(new java.awt.Color(0, 153, 102));
        btnNuevo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnNuevo.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevo.setText("Nuevo");
        btnNuevo.setBorder(null);
        btnNuevo.setBorderPainted(false);
        btnNuevo.setContentAreaFilled(false);
        btnNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNuevo.setOpaque(false);
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNuevo);
        btnNuevo.setBounds(160, 260, 80, 30);
        getContentPane().add(txbDescripcion);
        txbDescripcion.setBounds(20, 200, 260, 30);

        jLabel5.setText("Estado");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(460, 180, 70, 16);

        jLabel6.setText("Descripcion");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 180, 68, 16);

        cbxActivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activa", "Inactiva" }));
        getContentPane().add(cbxActivo);
        cbxActivo.setBounds(460, 200, 100, 30);
        getContentPane().add(txbCuenta);
        txbCuenta.setBounds(290, 200, 150, 30);

        jLabel7.setText("Cuenta Contable");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(290, 180, 93, 16);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        guardar();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        nuevaDepartamento();
    }//GEN-LAST:event_btnNuevoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox<String> cbxActivo;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblDepartamentos;
    private javax.swing.JTextField txbCuenta;
    private javax.swing.JTextField txbDescripcion;
    // End of variables declaration//GEN-END:variables

}
