package Views;

import Controladores.DaoEmpresa;
import Controladores.DaoNomina;
import DigyFenix.*;
import Enums.InsertUpdate;
import Modelos.Empresa;
import Modelos.Nomina;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author echacon
 */
public class VNomina extends javax.swing.JInternalFrame {

    HashMap<String, Object> mapFields = new HashMap<>();
    Nomina nom;
    DaoNomina daonom;

    /**
     * Creates new form v_empresa
     */
    public VNomina() {
        initComponents();

        //Inicio las variables
        nuevaNomina();
        daonom = new DaoNomina();

        //Configuro los botonos
        DFUtils.setColorABotton(btnGuardar);
        DFUtils.setColorABotton(btnNuevo);

        //generarSwitchMap();
        mapearFiels();

        llenarTablaNominas();

        nom.limpiarFields(true);
        nom.fieldsActivados(false);

        List<Empresa> emp = new DaoEmpresa().listar();
        emp.forEach((empresa) -> {
            cbxEmpresa.addItem(empresa.getDescripcion());
        });
    }

    private void mapearFiels() {
        System.out.println("mapearFiels:" + DFUtils.getMapearFiels(nom.getVariables()));
        mapFields.put("codigoNomina", txbCodigo);
        mapFields.put("descripcion", txbDescripcion);
        mapFields.put("activo", cbxActivo);
        nom.mapearFields(mapFields);
    }

    private void generarSwitchMap() {
        System.out.println("generarSwitchMap: " + DFUtils.getGenerarSwitchMap(nom.getVariables()));
        HashMap<String, DFMvcEnum> mapFields = new HashMap<>();
        mapFields.put("codigoNomina", DFMvcEnum.STRING);
        mapFields.put("descripcion", DFMvcEnum.STRING);
        mapFields.put("activo", DFMvcEnum.STRING);
        System.out.println(DFUtils.getSwitchParaMvc(mapFields));
    }

    private void guardar() {
        try {
            boolean nueva = (nom.getIdrhNomina() == null);
            //Primero se guardan los datos auxiliares para actualizar ids

            nom.setIdempresa((new DaoEmpresa().buscarPorDescripcion(cbxEmpresa.getSelectedItem().toString())).getIdrhEmpresa());

            String tipo = "";
            if (nueva) {
                daonom.insertarActualizar(nom, InsertUpdate.INSERTAR);
                tipo = "insertada";
            } else {
                daonom.insertarActualizar(nom, InsertUpdate.ACTUALIZAR);
                tipo = "actualizada";
            }
            llenarTablaNominas();
            DFOptionPane.mostrar_Realizado(nom.getClass().getSimpleName() + " " + tipo + " corretamente");
        } catch (Exception e) {
            DFOptionPane.mostrar_Error(e.toString());
        }
    }

    private void nuevaNomina() {
        nom = new Nomina();
        nom.mapearFields(mapFields);
        nom.limpiarFields(true);
        txbCodigo.requestFocus();
        nom.fieldsActivados(true);
    }

    private void llenarTablaNominas() {
        String encabezado[] = {"Id", "Empresa", "Codigo", "Descripcion", "Estado"};
        List<Nomina> list = daonom.listar();
        List<String[]> rows = new ArrayList<>();
        list.forEach((t) -> {
            String row[] = {"" + t.getIdrhNomina(), new DaoEmpresa().buscarPorId(t.getIdempresa()).getDescripcion(), t.getCodigoNomina(), t.getDescripcion(), t.getActivo()};
            rows.add(row);
        });

        DFTable.llenarTablaCol0NoEditable(tblNominas, encabezado, rows);
    }

    private void cargarDetalle(String id) {
        try {
            nom = daonom.buscarPorId(Integer.parseInt(id));
            cbxEmpresa.setSelectedItem(new DaoEmpresa().buscarPorId(nom.getIdempresa()).getDescripcion());
            nom.mapearFields(mapFields);
            nom.llenarFields();
            nom.fieldsActivados(true);
        } catch (Exception e) {
            DFOptionPane.mostrar_Error(e.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txbCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblNominas = new javax.swing.JTable();
        tblNominas.getSelectionModel().addListSelectionListener( 
            new ListSelectionListener(){
                public void valueChanged(ListSelectionEvent event){
                    if(!event.getValueIsAdjusting() && (tblNominas.getSelectedRow() >= 0)){
                        cargarDetalle(""+tblNominas.getValueAt(tblNominas.getSelectedRow(), 0));
                    }
                }
            }
        );
        btnNuevo = new javax.swing.JButton();
        txbDescripcion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbxActivo = new javax.swing.JComboBox<>();
        cbxEmpresa = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Administracion de nominas");
        setMaximumSize(new java.awt.Dimension(721, 377));
        setMinimumSize(new java.awt.Dimension(721, 377));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(721, 377));
        getContentPane().setLayout(null);
        getContentPane().add(txbCodigo);
        txbCodigo.setBounds(190, 210, 100, 30);

        jLabel2.setText("Codigo Diario");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(190, 190, 100, 20);

        btnGuardar.setBackground(new java.awt.Color(0, 153, 102));
        btnGuardar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.setBorder(null);
        btnGuardar.setBorderPainted(false);
        btnGuardar.setContentAreaFilled(false);
        btnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar.setOpaque(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar);
        btnGuardar.setBounds(440, 270, 80, 30);

        tblNominas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblNominas);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 10, 690, 160);

        btnNuevo.setBackground(new java.awt.Color(0, 153, 102));
        btnNuevo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnNuevo.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevo.setText("Nuevo");
        btnNuevo.setBorder(null);
        btnNuevo.setBorderPainted(false);
        btnNuevo.setContentAreaFilled(false);
        btnNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNuevo.setOpaque(false);
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNuevo);
        btnNuevo.setBounds(240, 270, 80, 30);
        getContentPane().add(txbDescripcion);
        txbDescripcion.setBounds(310, 210, 280, 30);

        jLabel5.setText("Estado");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(600, 190, 70, 16);

        jLabel6.setText("Descripcion");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(310, 190, 68, 16);

        cbxActivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activa", "Inactiva" }));
        getContentPane().add(cbxActivo);
        cbxActivo.setBounds(600, 210, 100, 30);

        getContentPane().add(cbxEmpresa);
        cbxEmpresa.setBounds(10, 210, 170, 30);

        jLabel9.setText("Empresa");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 190, 80, 16);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        guardar();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        nuevaNomina();
    }//GEN-LAST:event_btnNuevoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox<String> cbxActivo;
    private javax.swing.JComboBox<String> cbxEmpresa;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblNominas;
    private javax.swing.JTextField txbCodigo;
    private javax.swing.JTextField txbDescripcion;
    // End of variables declaration//GEN-END:variables

}
