package Views.Utils;

import DigyFenix.DFUtils;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author echacon
 */
public class VPreviewImg extends javax.swing.JInternalFrame {

    FondoPanel fondo;

    /**
     * Creates new form VPreviewImg
     *
     * @param imagen
     * @param segunRutaImagen
     */
    public VPreviewImg(String imagen, boolean segunRutaImagen) {
        initComponents();
        if (segunRutaImagen) {
            imagen = DFUtils.getRutaImagenes() + "\\" + imagen;
        }
        fondo = new FondoPanel(imagen);
        this.setContentPane(fondo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Visualizador de imagenes");
        setMaximumSize(new java.awt.Dimension(709, 532));
        setMinimumSize(new java.awt.Dimension(709, 532));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 707, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    class FondoPanel extends JPanel {

        private Image imagen;
        private String urlImagen;

        public FondoPanel(String img) {
            this.urlImagen = img;
        }

        @Override
        public void paint(Graphics g) {
            this.imagen = new ImageIcon(urlImagen).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
